# JupyterLab {#jupyter}

By default, notebooks are not trusted, to prevent them from executing malicious code. The following code will label a notebook as trustworthy.
```{python eval=FALSE}
jupyter trust my_notebook.ipyb
```

Here is a simple template that I use that controls a couple useful things when starting a new notebook.

```{python eval=FALSE}
import sys
sys.path.append('../util')

%reload_ext autoreload
%autoreload 2

from util import *
import numpy as np                  
import pandas as pd                 
from matplotlib import pyplot as plt
import seaborn as sns

sns.set_palette('pastel')
sns.set_style('ticks')
sns.set_context('paper', font_scale=1)
```

It is often convenient to have a notebook automatically refresh the imported libraries so that they can be modified while working on a JupyterLab notebook.

```{python eval=FALSE}
%reload_ext autoreload
%autoreload 2
```

To allow directory organization, dependcies can be separated into different directories and imported into a jupyter notebook using the following import statement.

```{python eval=FALSE}
import sys
sys.path.append('../util')
```

This is a simplified way to create a table of contents.
```{python eval=FALSE}
# Table of Contents
1. [Introduction](#Notebook-Setup)
2. [Parameters](#Parameters)
3. [Sample Processing](#Sample-Processing)
    1. [Variant Filtering](#Variant-Filtering)
```

A table of contents can be created to refer to each of the headers throughout a notebook in html format. The code is below (Obviously needs to be simplified.)
```{python eval=FALSE}
<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc">
    <ul class="toc-item">
    <li>
        <span><a href="#Python-Setup" data-toc-modified-id="Python-Setup-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Python Setup</a></span>
        <ul class="toc-item">
    <li>
        <span><a href="#Change-the-width-of-the-page" data-toc-modified-id="Change-the-width-of-the-page-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Change the width of the page</a></span></li>
        <li>
            <span><a href="#Import-packages" data-toc-modified-id="Import-packages-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Import packages</a></span></li>
        </ul>
    </li>
    <li>
        <span><a href="#Colours" data-toc-modified-id="Colours-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Colours</a></span>
        <ul class="toc-item">
    <li><span><a href="#Colour-line-graph" data-toc-modified-id="Colour-line-graph-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Colour line graph</a></span></li>
        </ul>
    </li>
    <li><span><a href="#Totals-for-studies" data-toc-modified-id="Totals-for-studies-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Totals for studies</a></span></li>
    <li><span><a href="#Functions-for-calculating-trinucleotide-context-specific-mutation-rates" data-toc-modified-id="Functions-for-calculating-trinucleotide-context-specific-mutation-rates-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Functions for calculating trinucleotide-context specific mutation rates</a></span>
        <ul class="toc-item">
        <li><span><a href="#Calculating-mutation-rates-for-individual-variants" data-toc-modified-id="Calculating-mutation-rates-for-individual-variants-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Calculating mutation rates for individual variants</a></span>
            <ul class="toc-item">
        <li><span><a href="#DNMT3A" data-toc-modified-id="DNMT3A-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>DNMT3A</a></span></li>
            <li><span><a href="#TET2" data-toc-modified-id="TET2-4.1.2"><span class="toc-item-num">4.1.2&nbsp;&nbsp;</span>TET2</a></span></li>
            <li><span><a href="#ASXL1" data-toc-modified-id="ASXL1-4.1.3"><span class="toc-item-num">4.1.3&nbsp;&nbsp;</span>ASXL1</a></span></li>
            <li><span><a href="#TP53" data-toc-modified-id="TP53-4.1.4"><span class="toc-item-num">4.1.4&nbsp;&nbsp;</span>TP53</a></span></li></ul></li>
        <li><span><a href="#Calculating-mutation-rates-from-a-.csv-file-of-variants" data-toc-modified-id="Calculating-mutation-rates-from-a-.csv-file-of-variants-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Calculating mutation rates from a .csv file of variants</a></span>
            <ul class="toc-item">
            <li><span><a href="#DNMT3A" data-toc-modified-id="DNMT3A-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>DNMT3A</a></span></li>
            <li><span><a href="#TET2" data-toc-modified-id="TET2-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>TET2</a></span></li>
            <li><span><a href="#ASXL1" data-toc-modified-id="ASXL1-4.2.3"><span class="toc-item-num">4.2.3&nbsp;&nbsp;</span>ASXL1</a></span></li>
            <li><span><a href="#TP53" data-toc-modified-id="TP53-4.2.4"><span class="toc-item-num">4.2.4&nbsp;&nbsp;</span>TP53</a></span></li></ul></li>
        <li><span><a href="#Calculating-mutation-rates-from-a-list-of-variants" data-toc-modified-id="Calculating-mutation-rates-from-a-list-of-variants-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Calculating mutation rates from a list of variants</a></span>
            <ul class="toc-item">
            <li><span><a href="#DNMT3A" data-toc-modified-id="DNMT3A-4.3.1"><span class="toc-item-num">4.3.1&nbsp;&nbsp;</span>DNMT3A</a></span></li>
        <li><span><a href="#TET2" data-toc-modified-id="TET2-4.3.2"><span class="toc-item-num">4.3.2&nbsp;&nbsp;</span>TET2</a></span></li>
            <li><span><a href="#ASXL1" data-toc-modified-id="ASXL1-4.3.3"><span class="toc-item-num">4.3.3&nbsp;&nbsp;</span>ASXL1</a></span></li>
            <li><span><a href="#TP53" data-toc-modified-id="TP53-4.3.4"><span class="toc-item-num">4.3.4&nbsp;&nbsp;</span>TP53</a></span></li></ul></li></ul></li>
    <li><span><a href="#Lists-of-variants-targeted-by-each-study" data-toc-modified-id="Lists-of-variants-targeted-by-each-study-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Lists of variants targeted by each study</a></span><ul class="toc-item"><li><span><a href="#Jaiswal-2014" data-toc-modified-id="Jaiswal-2014-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Jaiswal 2014</a></span></li>
        <li><span><a href="#Genovese-2014" data-toc-modified-id="Genovese-2014-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Genovese 2014</a></span></li>
        <li><span><a href="#McKerrel-2015" data-toc-modified-id="McKerrel-2015-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>McKerrel 2015</a></span></li>
        <li><span><a href="#Zink-2017" data-toc-modified-id="Zink-2017-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Zink 2017</a></span></li>
        <li><span><a href="#Coombs-2017" data-toc-modified-id="Coombs-2017-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Coombs 2017</a></span></li>
        <li><span><a href="#Young-2016-&amp;-2019" data-toc-modified-id="Young-2016-&amp;-2019-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>Young 2016 &amp; 2019</a></span></li>
        <li><span><a href="#Desai-2018" data-toc-modified-id="Desai-2018-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>Desai 2018</a></span></li>
        <li><span><a href="#Acuna-Hidalgo-2017" data-toc-modified-id="Acuna-Hidalgo-2017-5.8"><span class="toc-item-num">5.8&nbsp;&nbsp;</span>Acuna-Hidalgo 2017</a></span></li></ul></li>
    <li><span><a href="#Lists-of-all-possible-variants-in-DNMT3A,-TET2,-ASXL1,-TP53" data-toc-modified-id="Lists-of-all-possible-variants-in-DNMT3A,-TET2,-ASXL1,-TP53-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Lists of all possible variants in DNMT3A, TET2, ASXL1, TP53</a></span>
        <ul class="toc-item">
        <li><span><a href="#DNMT3A" data-toc-modified-id="DNMT3A-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>DNMT3A</a></span></li>
        <li><span><a href="#TET2" data-toc-modified-id="TET2-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>TET2</a></span></li>
        <li><span><a href="#ASXL1" data-toc-modified-id="ASXL1-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>ASXL1</a></span></li>
    <li><span><a href="#TP53" data-toc-modified-id="TP53-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>TP53</a></span></li></ul></li>
    <li><span><a href="#Actual-number-of-observations-of-each-variant" data-toc-modified-id="Actual-number-of-observations-of-each-variant-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Actual number of observations of each variant</a></span>
        <ul class="toc-item">
        <li>
            <ul class="toc-item">
            <li><span><a href="#DNMT3A" data-toc-modified-id="DNMT3A-7.0.1"><span class="toc-item-num">7.0.1&nbsp;&nbsp;</span>DNMT3A</a></span></li>
            <li><span><a href="#TET2" data-toc-modified-id="TET2-7.0.2"><span class="toc-item-num">7.0.2&nbsp;&nbsp;</span>TET2</a></span></li>
        <li><span><a href="#ASXL1" data-toc-modified-id="ASXL1-7.0.3"><span class="toc-item-num">7.0.3&nbsp;&nbsp;</span>ASXL1</a></span></li>
        <li><span><a href="#TP53" data-toc-modified-id="TP53-7.0.4"><span class="toc-item-num">7.0.4&nbsp;&nbsp;</span>TP53</a></span></li></ul></li></ul></li>
    <li><span><a href="#Functions-for-calculating-the-expected-number-of-observations-of-a-variant" data-toc-modified-id="Functions-for-calculating-the-expected-number-of-observations-of-a-variant-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Functions for calculating the expected number of observations of a variant</a></span></li>
    <li><span><a href="#Maximum-Likelihood-Estimation-for-s" data-toc-modified-id="Maximum-Likelihood-Estimation-for-s-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Maximum Likelihood Estimation for s</a></span>
        <ul class="toc-item"><li><span><a href="#DNMT3A-variants" data-toc-modified-id="DNMT3A-variants-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>DNMT3A variants</a></span></li>
        <li><span><a href="#TET2-variants" data-toc-modified-id="TET2-variants-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>TET2 variants</a></span></li>
        <li><span><a href="#ASXL1-variants" data-toc-modified-id="ASXL1-variants-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>ASXL1 variants</a></span></li>
        <li><span><a href="#TP53-variants" data-toc-modified-id="TP53-variants-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>TP53 variants</a></span></li>
        </ul>
        </li>
    </ul>
</div>
```
