# Bioinformatics Resources {#resources}

## Cancer Datasets
* [The Cancer Cell Line Encyclopedia](https://www.nature.com/articles/s41586-019-1186-3?WT.ec_id=NATURE-201905&sap-outbound-id=720FBE4668F2FE14A299D42CB43EF50D90063A16&mkt-key=005056A5C6311ED999AC3A52796F7641) has a wealth of information from a large number of cancer cell lines.
* [Project score](https://score.depmap.sanger.ac.uk/) has a number of genetic screens that may be useful in identifying pathways that are critical to cancer growth and survival
* [cbioportal](http://www.cbioportal.org/) has information about codon changes in cancer but does not seem to have any sequence data
* [dbGAP](https://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?page=login) has info on genotypes and phenotypes, whatever the fuck that means
	+ [Here](https://dbgap.ncbi.nlm.nih.gov/aa/wga.cgi?page=login) is the page with instructions on how to get dbGAP access
* [TCGA](https://www.cancer.gov/about-nci/organization/ccg/research/structural-genomics/tcga)
	+ [This](https://gdc.cancer.gov/access-data/obtaining-access-controlled-data) page has the instructions on how to get TCGA access
* [COSMIC](https://cancer.sanger.ac.uk/cosmic)
	+ Cosmic has a project called the [Cancer Gene Census](https://cancer.sanger.ac.uk/cosmic/census?genome=37) in which they are trying to catalog all mutations that have been implicated in playing a causal role in cancer
	+ They also have implemented convenient [ways](https://cancer.sanger.ac.uk/cosmic/help/file_download) of directly downloading information and files from the database in python using the files hosted [here](https://cancer.sanger.ac.uk/cosmic/download).
* [Mastermind](https://mastermind.genomenon.com/api) from genomenon parsed all the articles on pubmed in order to find any and all information for each possible mutation
* [GTEx](https://gtexportal.org/home/) has RNA-Seq, Exome Seq, WGseq, SNP arrays, gene expression arrays and more for cancer and non-cancer? 

## Alzheimer's
* [The Alzheimers sequencing project](https://www.niagads.org/adsp/content/home) is gathering data to understand late onset alzheimer's

## Genomic Datasets 
* [AllOfUs](ttps://www.joinallofus.org/en/how-to-join) is sequencing and collecting other health data on a million individuals
* [Color Genomics](https://www.color.com/) is one of three companies that will be doing the sequencing and testing for AllOfUs
* [1000 genomes](http://www.internationalgenome.org/data/)
* [100,000 genomes](https://www.genomicsengland.co.uk/)
