# Golang {#golang}

## Installation
Installation of linuxbrea
```{bash eval=FALSE}
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
# Add to path
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
# debian/ubuntu dependencies
sudo apt-get install build-essential curl file git
```

LinuxBrew golang installation
```{bash eval=FALSE}
brew install go
```

The GO PATH should then be checked; it should typically exist at ~/go but it can be checked like this
```{bash eval=FALSE}
echo $GOPATH
```

## Updating
```{bash eval=FALSE}
brew install dep
brew upgrade dep
brew cask install spotify
```

## Sample Program
Create a file called hello.go
```{python eval=FALSE}
package main

import "fmt"

func main() {
	fmt.Printf("hello, world\n")
}

The program can just be run with
go run main.go

Then compile the program
	go build

Importing multiple things can be done on one line separated by a semicolon
	import ("fmt"; "math")
```

## Type conversion
Check the type of a variable
```{python eval=FALSE}
import("fmt";"reflect")
i := 5
fmt.Println(reflect.TypeOf(i))
```

Convert int to float64
```{python eval=FALSE}
var i int = 5
j := float64(i)
```

int to string
```{python eval=FALSE}
s := strconv.Itoa(97) // s == "97"
```

int64 to string
```{python eval=FALSE}
var n int64 = 97
s := strconv.FormatInt(n, 10) // s == "97" (decimal) in base 10
```

string to int
```{python eval=FALSE}
s := "97"
if n, err := strconv.Atoi(s); err == nil {
    fmt.Println(n+1)
} else {
    fmt.Println(s, "is not an integer.")
}
```

string to int64
```{python eval=FALSE}
s := "97"
n, err := strconv.ParseInt(s, 10, 64)
if err == nil {
    fmt.Printf("%d of type %T", n, n)
}
```

int to int64
```{python eval=FALSE}
var n int = 97
m := int64(n) // safe
```

## Strings
Numbers can be converted to strings using strconv
```{python eval=FALSE}
s := strconv.FormatFloat(3.1415, 'E', -1, 64)
s := strconv.FormatInt(-42, 16)
```

Strings can be assigned with ` ` or " ", but only the double quotes can use escape characters like newlines \n or \t
```{python eval=FALSE}
fmt.Println("Hello\n World")
```

Indexing returns bytes rather than strings so they must be converted if you want a string back
```{python eval=FALSE}
string("Hello World"[1])
```

Test if a string is a substring of another
```{python eval=FALSE}
import "strings"
strings.Contains("something","some") // true
```

## Boolean Functions
	&&, ||, !, true, false

## Variables
Variables are statically typed and therefore must be declared when assigned
```{python eval=FALSE}
var x string = "Hello World"
```

Type declaration can be offloaded to the compiler using the following notation, and the compiler will try to infer the correct type
```{python eval=FALSE}
var x = "Hello World"
x := "Hello World"
```

Constants are similar to variables, but their values cannot be reassigned
```{python eval=FALSE}
const x string = "Hello"
```

Multiple variables can also be declared at once, where each variable must occupy its own line
```{python eval=FALSE}
var (
	a = 5
	b = 10
	c = 15
)
```

Substrings
```{python eval=FALSE}
s := "something"
fmt.Println(s[:len(s)-5])
fmt.Println(s[2:6])
```

## Input
User input
```{python eval=FALSE}
var input float64
fmt.Scanf("%f", &input)
```

## Control Structures
For loops can be written like the following
```{python eval=FALSE}
i := 1
for i <= 10 {
	fmt.Println(i)
	i += 1
}
```
The variables a function will return can be defined at the beginning of the functions and then implicitely returned.
```{python eval=FALSE}
func something(x int) (product int) {
    product = x * x
    return
}
```

Probably the easier for loop is like this one
```{python eval=FALSE}
for i := 1; i <= 10; i++ {
	fmt.Println(i)
}
```

A nice for loop to iterate through a range
```{python eval=FALSE}
for i := range str1 {
    if str1[i] == str2[i] { count++ }
}
return count
```

For loops can be used to iterate through slices too
```{python eval=FALSE}
for _, num := range nums {
```

If loops look gross, but it is required that the else statement is placed where it is shown here
```{python eval=FALSE}
if true {
} else if false {
}
```

Switches are also a thing
```{python eval=FALSE}
switch input {                          
	case 1: fmt.Println("You entered one")  
	case 2: fmt.Println("You entered two")  
	case 3: fmt.Println("You entered three")
}                                           
```

## Data Structures
A blank array
```{python eval=FALSE}
var x []int
```

An array with five elements
```{python eval=FALSE}
var x [5]int
x[0] = 50 // the first element of the array equals 50
```

An easier way to create an array and can be multiline broken by the commas
```{python eval=FALSE}
x := [5]float64{ 98, 93, 77, 82, 83 }
```

Slices can have variable lengths and are typically associated with an array of fixed length. The following slice is 5 elements long, and is a segment of a 10 element-long array
```{python eval=FALSE}
x := make([]float64, 5, 10)
```

In a way that seems more similar to python, slicing an array can be done like this
```{python eval=FALSE}
arr := [5]float64{1,2,3,4,5}
x := arr[0:2]
```

Adding data to a slice
```{python eval=FALSE}
slice1 := []int{1,2,3}
slice2 := append(slice1,4,5)
```

Or multiple values can be added at once
```{python eval=FALSE}
s = append(s, 2, 3, 4)
```

A map is an unordered collection of key-value pairs (also known as a dictionary). A map is defined by assigning it to a variable and then defining the key type in brackets and the value type after the brackets
```{python eval=FALSE}
var x make(map[string]int)
x["key"] = 10 
fmt.Println(x)
```

Creating a map with multiple items simultaneously
```{python eval=FALSE}
elements := map[string]string{
  "H":  "Hydrogen",
  "He": "Helium",
  "Li": "Lithium",
}
```

Items can be deleted from a map using the delete function
```{python eval=FALSE}
delete(x, "key")
```

Go provides functionality that checks whether a key lookup from a map was successful or not
```{python eval=FALSE}
m,n := x["unknown"] // this key does not exist
fmt.Println(m,n) // m will equal 0 and n will equal false
```

This check can be used in an if loop to only run a chunk of code if a key exists within a map. In the below code el equals the value and ok is true or false, if the key is found, ok equals true and the print statement is run
```{python eval=FALSE}
if el, ok := elements["Li"]; ok {
fmt.Println(el["name"], el["state"])
}
```

Iterate through a map
```{python eval=FALSE}
for k, v := range kmers {                  
    fmt.Printf("key: %s value: %d\n", k, v)
}
```

## Functions
Below is a basic function that computes the mean of a map
```{python eval=FALSE}
func average(xs []float64) (float64) {
    total := 0.0                      
    for _, v := range xs {            
        total += v                    
    }
    return total / float64(len(xs))   
}                                     
```

A function can also take multiple different types of variables
```{python eval=FALSE}
func lots_of_stuff(a int, b map[string]int64, c float64) (string, string, int64) {
// do stuff
}
```

If it is desirable that a function takes maps of variable lengths a function can be designed like the one below
```{python eval=FALSE}
func add(args ...int) int { 
    total := 0              
    for _, v := range args {
        total += v          
    }                       
    return total            
}  
```

Functions can also be placed within other functions like this
```{python eval=FALSE}
func main() {
  add := func(x, y int) int {
    return x + y
  }
  fmt.Println(add(1,1))
}
```
                         
Closure refers to functions that utilize non-local variables
```{python eval=FALSE}
func main() {
  x := 0
  increment := func() int {
    x++
    return x
  }
  fmt.Println(increment())
  fmt.Println(increment())
}
```

Recursion uses the same function recursively
```{python eval=FALSE}
// a recursive function      
func factorial(x uint) uint {
    if x == 0 {              
        return 1             
    }                        
    return x * factorial(x-1)
}      
```

Deferring essentially moves a function call to the end of a function, like the following which closes the file after it is used
```{python eval=FALSE}
f, _ := os.Open(filename)
defer f.Close()
```

## While loops
These are not actually included in golang as in other languages but instead utilize for loops.

This is a repeat-until loop:
```{python eval=FALSE}
for {
    work()
    if condition {
        break
    }
}
```
or
```{python eval=FALSE}
for ok := true; ok; ok = !condition {
    work()
}
```

A do-while loop
```{python eval=FALSE}
for {
    work()
    if !condition {
        break
    }
}
```
or
```{python eval=FALSE}
for ok := true; ok; ok = condition {
    work()
}
```

## Timing a function
```{python eval=FALSE}
start := time.Now()
t := time.Now()
elapsed := t.Sub(start)
fmt.Println(elapsed)
```

## Pointers
Pointers can be used to access the memory location of a variable and alter the value stored in that location

```{python eval=FALSE}
func zero(xPtr *int) {                                              
    *xPtr = 0 // asterisk signifies a pointer                                                       
}                                                                   
                                                                    
func main() {                                                       
    x := 5                                                          
    zero(&x) // & finds the address of a variable                                                       
    fmt.Println(x) // using a pointer allows the value to be changed
}                                                                   
```

There is a built in function called new that takes a type as an argument, and allocates sufficient memory to hold that type and returns a pointer to it, and unlike other languages, because go is a garbage collected language, it will delete anything created by new when nothing refers to it anymore

```{python eval=FALSE}
func one(xPtr *int) {
    *xPtr = 1        
}
                    
func main() {                                                                                                                 
    xPtr := new(int)                                                
    one(xPtr)                                                       
    fmt.Println(*xPtr)                                              
}                                                                   
```

## Structures
These seem similar to classes and allow a new 'type' to be created
```{python eval=FALSE}
type Circle struct {
x float64
y float64
r float64

	// values of the same type can be combined like this
	x, y, r float64 
}                   
```

A new structure can be created just like a typical variable
```{python eval=FALSE}
var c Circle
```

A structure can be created like pointers which will set all values to their zero value like 0, 0.0, "" and return a pointer
```{python eval=FALSE}
c := new(Circle)
```

Values for a structure can also be defined at variable creation time
```{python eval=FALSE}
c := Circle{x: 0, y: 0, r: 5}
// this is possible if you remember the order vars were defined
c := Circle{0, 0, 5}
```

Structure fields are accessed like class methods
```{python eval=FALSE}
fmt.Println(c.x, c.y, c.r)
c.x = 10
c.y = 5
```

When passing a structure to another function, its type is the name of the structure
```{python eval=FALSE}
func circleArea(c Circle) float64 {
    return math.Pi * c.r * c.r     
}                                  
```

Fields of a structure that has been defined are not altered unless a pointer is used
```{python eval=FALSE}
func circleArea(c *Circle) float64 {
    c.r = 10                        
    return math.Pi * c.r * c.r      
}                                   
                                    
func main() {                       
    c:= Circle{0, 0, 5}             
    fmt.Println(circleArea(&c), c)  
}
```

## Methods
These can be added to structures so they can be directly accessed by automatically passing a pointer to the method. The area() receiver can be used for other structures, and does not have to be a unique word
```{python eval=FALSE}
type Circle struct {             
    x, y, r float64              
}                                
                                 
func (c *Circle) area() float64 {
    return math.Pi * c.r * c.r   
}                                
                                 
func main() {                    
    c:= Circle{0, 0, 5}          
    fmt.Println(c.area())        
}   
```

Embedded Types is sort of like inheritance and gives a method access to all of the features of another structure.

Here is a person structure                            
```{python eval=FALSE}
type Person struct {
  Name string
}
func (p *Person) Talk() {
  fmt.Println("Hi, my name is", p.Name)
}
```

Here Android is defined to have the same properties as the person structure
```{python eval=FALSE}
type Android struct {
  Person
  Model string
}

a := new(Android)
a.Talk()
```

## Packaging
Building code into a package is a convenient way of then accessing the same methods without having to rebuild them.

To create a package, make a folder with the same name as the package so `math` in this case. Then refer to the package name in a file within this folder like this:
package math                        
                                    
```{python eval=FALSE}
func Average(xs []float64) float64 {
    total := float64(0)             
    for _, x := range xs {          
        total += x                  
    }                               
    return total / float64(len(xs)) 
}                                   
```

Then save this file and build it from the same directory using:
```{python eval=FALSE}
go install
```

Finally, use this package by referring to its directory like this:
```{python eval=FALSE}
package main                          
                                      
import "fmt"                          
// import "chapter11/math" //this format can be used if put in ~/go/src/
import "./math"                       
                                      
func main() {                         
    xs := []float64{1,2,3,4}          
    avg := math.Average(xs)           
    fmt.Println(avg)                  
}                                     
```

## Read/Write Files
Here is how a file is opened
```{python eval=FALSE}
f, err := os.Open("./data/genomes/schisto_small.fa")
check(err)
f.Close() // when done

func check(e error) {
    if e != nil {    
        panic(e)     
    }                
}
```

In Go 2.0 the `try` function can be used to open files a bit more elegantly.
Instead of this:
```{python eval=FALSE}
f, err := os.Open(filename)
    if err != nil {
        return …, err
    }
```
Opening is simplified to this:
```{python eval=FALSE}
f := try(os.Open(filename))
```

Read by a certain number of bytes at a time
```{python eval=FALSE}
b1 := make([]byte, 61)                      
n1, err := f.Read(b1)                       
check(err)                                  
fmt.Printf("%d bytes: %s\n", n1, string(b1))
```

Peek might be more efficient with many small read calls but reads next n bytes without advancing the reader                                                       
```{python eval=FALSE}
r4 := bufio.NewReader(f)                                  
b4, err := r4.Peek(61)                                    
check(err)                                                
fmt.Printf("5 bytes: %s\n", string(b4))
```

Scanners are useful ways to read newline delimited files
```{python eval=FALSE}
scanner := bufio.NewScanner(f)                             
for scanner.Scan() {                                       
    fmt.Println(scanner.Text()) // Println retains the \n  
}                                                          
if err := scanner.Err(); err != nil {                      
    fmt.Fprintln(os.Stderr, "reading standard input:", err)
}
```

Read from gzip file
```{python eval=FALSE}
import("compress/gzip")                                                          
file, err := os.Open("./data/genomes/schisto_small_2.fa.gz")
f, err := gzip.NewReader(file)
```
